# Don't change this! Version used to track needed updates.
version = 0
debugLogging = false

[PARTS]
headWeight = 5.0
headFatal = true
torsoWeight = 5.0
torsoFatal = true
armWeight = 1.0
legWeight = 2.0
headArmorPadding = 0.25
headToughnessPadding = 0.25

[ITEMS]
morphineUseTime = 32
morphineDuration = 3600
additionalMorphineTime = true
additionalMorphineTimeModifier = 1000
allowOverdosing = true
bandageUseTime = 36
bandageHealAmount = 3.0
bandageThreshold = 0.5
medkitMaxUses = 3